import type { Product } from "@shared/schema";

export const fallbackProducts: Product[] = [
  {
    id: 1,
    name: "The Royal Princess",
    description: "A stunning princess-cut diamond set in 18k white gold, surrounded by a halo of smaller diamonds.",
    price: "4500.00",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    category: "Engagement",
    metalType: "Gold",
    caratWeight: "1.5",
    clarity: "VVS1",
    color: "E",
    cut: "Princess",
    rating: "4.9",
    reviewsCount: 124,
  },
  {
    id: 2,
    name: "Eternal Love Band",
    description: "A classic eternity band featuring brilliant-cut diamonds encircling the entire ring.",
    price: "2800.00",
    imageUrl: "https://images.unsplash.com/photo-1603561591411-07134e71a2a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    category: "Wedding",
    metalType: "Platinum",
    caratWeight: "2.0",
    clarity: "VS1",
    color: "F",
    cut: "Round",
    rating: "4.8",
    reviewsCount: 89,
  },
  {
    id: 3,
    name: "Rose Gold Solitaire",
    description: "A minimalist solitaire diamond ring set in a warm rose gold band.",
    price: "3200.00",
    imageUrl: "https://images.unsplash.com/photo-1599643478518-17488fbbcd75?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    category: "Engagement",
    metalType: "Gold",
    caratWeight: "1.2",
    clarity: "VVS2",
    color: "G",
    cut: "Round",
    rating: "5.0",
    reviewsCount: 210,
  },
  {
    id: 4,
    name: "Sapphire & Diamond Halo",
    description: "A magnificent blue sapphire surrounded by a halo of sparkling diamonds.",
    price: "5600.00",
    imageUrl: "https://images.unsplash.com/photo-1588444650733-d0767b753fc8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    category: "Fashion",
    metalType: "Silver",
    caratWeight: "2.5",
    clarity: "VS2",
    color: "H",
    cut: "Oval",
    rating: "4.7",
    reviewsCount: 56,
  },
  {
    id: 5,
    name: "Vintage Art Deco",
    description: "An intricate vintage-inspired design with detailed milgrain work.",
    price: "6200.00",
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    category: "Engagement",
    metalType: "Platinum",
    caratWeight: "1.8",
    clarity: "VVS1",
    color: "D",
    cut: "Emerald",
    rating: "4.9",
    reviewsCount: 78,
  },
  {
    id: 6,
    name: "Modern Tension Set",
    description: "A contemporary tension-set ring that appears to float the diamond in mid-air.",
    price: "3900.00",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
    category: "Fashion",
    metalType: "Gold",
    caratWeight: "1.0",
    clarity: "IF",
    color: "D",
    cut: "Round",
    rating: "4.6",
    reviewsCount: 45,
  },
];
